# Generated by Django 5.1.2 on 2024-10-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_form_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='date',
            new_name='mydate',
        ),
    ]
