# Generated by Django 5.1.2 on 2024-10-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_date_form_mydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='mydate',
        ),
    ]
