# Generated by Django 5.1.2 on 2024-11-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
